version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    image: app/react-image
    container_name: app_container
    command: npm start