version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: react-app/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    image: app/react
    container_name: app_container
    command: npm start